#! /usr/bin/env node_modules/.bin/babel-node

import ygor from 'ygor';
import * as reader from '../lib/reader';
import { writeBuilder } from '../lib/writer';
import Builder from '../lib/builder';
import { validateBuilder } from '../lib/validator';
import { Package } from '../lib/models';
import { task } from '../lib/utils';

// Assembles data from YAML files in memory and validates them. does not save the data
export async function buildData() {

  // directory where all the yaml files are stored
  const inputDir = ygor.cli.inputDir || 'data';

  // create a new content builder: this will stop duplicates content items
  // and ensure the data is composed correctly according to models we expect
  const builder = new Builder();

  // process packages.yaml: read file and add content items to the builder
  await reader.packages(builder, inputDir, 'packages.yaml');

  // process articles.yaml: read file and add content items to the builder
  await reader.articles(builder, inputDir, 'articles.yaml');

  // Turn on debugging output
  if (ygor.cli.dump) {
    const filter = typeof ygor.cli.dump === 'string' ? ygor.cli.dump.split(/[,\ ]+/) : null;
    Builder.dump(builder, filter);
  } else if (typeof ygor.cli.package === 'string') {
    builder.content.forEach((content) => {
      if (!(content instanceof Package)) return;
      if (ygor.cli.package !== content.uuid) return;
      content.dumpContents();
    });
  }

  // validate all the content
  validateBuilder(builder);

  return builder;
}

// Read YAML files, assemble content items and save each item as a JSON file
export async function writeData() {

  // local directory where all the json files should be saved
  const outputDir = ygor.cli.outputDir || '.tmp';

  // create the outputDir if not already present
  ygor.shell(`mkdir -p ${outputDir}`);

  // clean the outputDir directory
  ygor.shell(`rm -rf ${outputDir}/*`);

  if (ygor.cli.removeAll) {
    console.log(`Exiting early, leaving outputDir empty. (outputDir=${outputDir})`);
    return;
  }

  // Assemble all the data from YAML files
  const builder = await buildData();

  // write the contents of the builder to disk
  // each content item is a separate JSON file
  await writeBuilder(builder, outputDir);

  // Output a list of all the files created
  console.log('');
  console.log('Write content:');
  console.log('');
  console.log([...builder.content.values()].map(item => `${outputDir}/${item.filename}`).join('\n'));
}

ygor.task('default', task(writeData))
    .task('write', task(writeData))
    .task('data', task(buildData));
